# Generated by Django 5.1.5 on 2025-01-17 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=2000)),
                ("pages", models.IntegerField()),
                ("author", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
                ("imgLink", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="miLectura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField()),
                ("currentPage", models.IntegerField()),
                ("calification", models.IntegerField()),
                ("comments", models.TextField(max_length=500)),
                ("startReading", models.DateField(blank=True, null=True)),
                ("finishReading", models.DateField(blank=True, null=True)),
                (
                    "Book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecturas",
                        to="appBook.books",
                    ),
                ),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="libros_leidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("User", "Book")},
            },
        ),
    ]
