# Generated by Django 5.1.5 on 2025-01-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appBook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="milectura",
            name="bookType",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="milectura",
            name="comments",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="milectura",
            name="state",
            field=models.CharField(max_length=50),
        ),
    ]
