# Generated by Django 5.1.5 on 2025-01-19 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appBook", "0002_milectura_booktype_alter_milectura_comments_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MyReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=50)),
                ("currentPage", models.IntegerField()),
                ("calification", models.IntegerField()),
                ("comments", models.TextField(blank=True, max_length=500)),
                ("startReading", models.DateField(blank=True, null=True)),
                ("finishReading", models.DateField(blank=True, null=True)),
                ("bookType", models.CharField(max_length=50)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecturas",
                        to="appBook.books",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="libros_leidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "book")},
            },
        ),
        migrations.DeleteModel(
            name="miLectura",
        ),
    ]
