# Generated by Django 5.1.5 on 2025-02-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appBook", "0003_myreading_delete_milectura"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myreading",
            name="calification",
            field=models.IntegerField(blank=True),
        ),
    ]
