# Generated by Django 5.1.5 on 2025-02-09 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appBook", "0003_myreading_delete_milectura"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Books",
            new_name="Book",
        ),
    ]
