# Generated by Django 5.1.5 on 2025-02-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appBook", "0004_rename_books_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myreading",
            name="calification",
            field=models.IntegerField(null=True),
        ),
    ]
