# Generated by Django 5.1.5 on 2025-02-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appBook", "0004_alter_myreading_calification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myreading",
            name="calification",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
