# Generated by Django 5.1.5 on 2025-02-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appBook", "0005_alter_myreading_calification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myreading",
            name="comments",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
