# Generated by Django 5.1.5 on 2025-02-09 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appBook", "0006_alter_myreading_comments"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Books",
            new_name="Book",
        ),
    ]
